[package]
name = "browserslist-data"
version = "0.2.0"
authors = ["Pig Fang <g-plane@hotmail.com>"]
edition = "2024"
description = "Data for browserslist-rs."
repository = "https://github.com/browserslist/browserslist-rs"
license = "MIT"
include = [
    "**/*.rs",
    "Cargo.toml",
    "src/generated/info.txt",
    "src/generated/**/*.bin",
    "src/generated/**/*.bin.deflate",
]

[dependencies]
ahash = { workspace = true }
chrono = { workspace = true }
miniz_oxide = { version = "0.9.1", optional = true, default-features = false, features = ["with-alloc"] }

[features]
deflate = ["dep:miniz_oxide"]
